service: todo-app-backend

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1

functions:
  tasks:
    handler: tasks.handler
    events:
      - http:
          method: get
          path: tasks
          cors: true
      - http:
          method: post
          path: tasks
          cors: true
      - http:
          method: put
          path: tasks/{taskId}
          cors: true
      - http:
          method: delete
          path: tasks/{taskId}
          cors: true
